import { InputHTMLAttributes, forwardRef, useRef, useId } from 'react';

import { useInputContext } from '../InputProvider';
import type { InputSize, InputStatus } from '../types';
import { useFileInput } from './hooks/useFileInput';
import * as S from './InputField.styles';

export interface InputFieldProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
  type?: React.HTMLInputTypeAttribute;
  size?: InputSize;
  status?: InputStatus;
  disabled?: boolean;
  readOnly?: boolean;
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  endButton?: React.ReactNode;
}

const InputField = forwardRef<HTMLInputElement, InputFieldProps>(
  (
    {
      id: idProp,
      type,
      size: sizeProp,
      status: statusProp,
      disabled: disabledProp,
      readOnly: readOnlyProp,
      startIcon,
      endIcon,
      endButton,
      onChange,
      ...rest
    },
    ref,
  ) => {
    const context = useInputContext();
    const internalRef = useRef<HTMLInputElement>(null);
    const autoGeneratedId = useId();

    const inputSize = context?.size ?? sizeProp ?? 'medium';
    const status = statusProp ?? 'default';
    const disabled = disabledProp ?? false;
    const readOnly = readOnlyProp ?? false;
    const inputId = idProp ?? autoGeneratedId;
    const isFileInput = type === 'file';

    const {
      selectedFileName,
      isDragging,
      handleFileChange,
      handleDragOver,
      handleDragLeave,
      handleDrop,
    } = useFileInput({ disabled, onChange });

    const handleWrapperClick = () => {
      const inputElement =
        ref && 'current' in ref ? ref.current : internalRef.current;

      if (isFileInput) {
        inputElement?.click();
      } else {
        inputElement?.focus();
      }
    };

    return (
      <S.Wrapper
        inputSize={inputSize}
        status={status}
        disabled={disabled}
        readOnly={readOnly}
        isFileInput={isFileInput}
        isDragging={isDragging}
        onClick={handleWrapperClick}
        onDragOver={isFileInput ? handleDragOver : undefined}
        onDragLeave={isFileInput ? handleDragLeave : undefined}
        onDrop={
          isFileInput
            ? (e) => {
                const inputElement =
                  ref && 'current' in ref ? ref.current : internalRef.current;
                handleDrop(e, inputElement);
              }
            : undefined
        }
      >
        {startIcon && <S.IconSlot>{startIcon}</S.IconSlot>}
        <S.NativeInput
          ref={ref ?? internalRef}
          id={inputId}
          type={type}
          disabled={disabled}
          readOnly={readOnly}
          isFileInput={isFileInput}
          aria-invalid={status === 'error'}
          onChange={isFileInput ? handleFileChange : onChange}
          {...rest}
        />
        {isFileInput && (
          <S.FileInputContent>
            <S.FileInputButton>파일 선택</S.FileInputButton>
            <S.FileInputText>
              {selectedFileName || '선택된 파일 없음'}
            </S.FileInputText>
          </S.FileInputContent>
        )}
        {!isFileInput && endButton && <S.ButtonSlot>{endButton}</S.ButtonSlot>}
        {!isFileInput && !endButton && endIcon && (
          <S.IconSlot>{endIcon}</S.IconSlot>
        )}
      </S.Wrapper>
    );
  },
);

InputField.displayName = 'InputField';

export default InputField;
